version: '3'
services:
  php-book-app-web:
    container_name: php-book-app-web
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_DEFAULT_LOCALE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
      - DATABASE_HOST=php-book-app-db
      - DATABASE_USER=root
      - DATABASE_PASS=secret
      - DATABASE_NAME=qa_app
    command: bash -c "sh docker-init-setup.sh && apache2-foreground"
    ports:
      - "80:80"

  php-book-app-db:
    container_name: php-book-app-db
    restart: always
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./Docker/mysql/sqls:/docker-entrypoint-initdb.d
      - ./Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "13306:3306"

  php-book-app-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-book-app-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=php-book-app-db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - php-book-app-db
    ports:
      - 8080:80
    volumes:
      - /sessions

  php-book-app-smtp:
    image: schickling/mailcatcher
    container_name: php-book-app-smtp
    ports:
     - "1080:1080"
     - "25:1025"

  swagger:
    image: swaggerapi/swagger-editor
    # volumes:
    #   - ./docker/swagger/${SWAGGER_YAML}:/usr/share/nginx/html/${SWAGGER_YAML}
    # environment:
    #   API_URL: ${SWAGGER_YAML}
    ports:
      - 8000:8080

  php-book-app-watch:
    image: node:12
    container_name: php-book-app-watch
    working_dir: /home/app
    command: "npm run watch"
    volumes:
      - ./app:/home/app
    ports:
      - "3000:3000"
      - "3001:3001"